### ISSUE TITLE
Arc for diagonal data…

### ISSUE THREAD

**Issue by zedrdave** [shahinrostami/chord#37] opened 2021-04-10 23:35 UTC
While testing with the non-pro version, it seemed that diagonal data (number of instances from a node to itself) were ignored: the area was shown on the outer circle, but no arc was plotted.

With the Pro version, there is an arc to itself (which essentially looks like a half ellipse). Is there a way to obtain the behaviour of the non-Pro version (diagonal data used for scale of each node, but no arc)?

**Comment by shahinrostami** [comment] 2021-04-11 07:52
Hi @zedrdave 

The `pro` version has the defined and intended behaviour for entries in the diagonal of the matrix. 

Can you share a minimal example (code + screenshot) that demonstrates the output you're after? I'm happy to take feature requests, so I could add this one to the list!

**Comment by zedrdave** [comment] 2021-04-11 08:50
I can understand that this would be the preferred default behaviour. It would be great if there was a flag option to disable it.

It's fairly simple to reproduce, using the default sample code with some values added along the diagonal, eg:
```
matrix = [
    [19, 5, 6, 4, 7, 4],
    [5, 4, 5, 4, 6, 5],
    [6, 5, 0, 4, 5, 5],
    [4, 4, 4, 0, 5, 5],
    [7, 6, 5, 5, 0, 4],
    [4, 5, 5, 5, 4, 0],
]
```

Calling `Chord(matrix, names)` then gives this in non-Pro mode:
<img width="405" alt="Screenshot 2021-04-11 at 10 47 04" src="https://user-images.githubusercontent.com/746979/114297904-af8cdd00-9ab3-11eb-906c-3c1e8626795d.png">

but this in Pro mode:
<img width="546" alt="Screenshot 2021-04-11 at 10 47 27" src="https://user-images.githubusercontent.com/746979/114297909-b9164500-9ab3-11eb-8682-0eaea393d5d8.png">

I looked for a possible option that controls this behaviour, but couldn't find it.

**Comment by shahinrostami** [comment] 2021-04-11 09:44
Thank you for the screenshot, I understand exactly what you mean now!

I don't think it will be too troublesome to implement a flag for that so I'll put it on top of the list. I was planning to work on `chord pro` tonight so I'll try slip this in to the update. I'll ping you on this issue when it's done 👍

**Comment by shahinrostami** [comment] 2021-04-11 14:25
Hey @zedrdave, pinging you as promised!

I've reproduced the desired `chord free` for `chord pro` under the parameter `colored_labels` being set to `False`. This is available in version `1.0.0` of  `chord` (please update with `pip`!).

There's an example in the documentation [1] and here's a screenshot too:

<img width="741" alt="Screenshot 2021-04-11 at 15 23 05" src="https://user-images.githubusercontent.com/15690380/114307925-d5c57380-9ad9-11eb-88ed-146c455fc82b.png">

It was nice to get some time to work on `chord pro`, thank you for your suggestion 👍 

[1] https://datacrayon.com/posts/statistics/data-is-beautiful/chord-pro-features-for-chord-diagrams/#Colored-Diagonals

**Comment by zedrdave** [comment] 2021-04-11 14:38
Thanks a lot for your reactivity and fast work on this! I'll test it and let you know if there's any problem…

Since we're in suggestion mode: may I suggest perhaps extending the current templating approach (`verb`, `noun`) to something more generic and broader: eg passing a Python-style or JS-style f-string that gets used as template…

**Comment by shahinrostami** [comment] 2021-04-11 14:46
> Thanks a lot for your reactivity and fast work on this! I'll test it and let you know if there's any problem…

My pleasure :) I'll close this for now but please re-open you spot anything wrong with it.

> Since we're in suggestion mode: may I suggest perhaps extending the current templating approach (`verb`, `noun`) to something more generic and broader: eg passing a Python-style or JS-style f-string that gets used as template…

This one is actually already on my list! I won't be removing the existing parameters (to maintain some backwards compatibility), but I will be adding a new overriding parameter to specify a template.

The main challenge for me is finding time to work on it! The lifetime license model I'm using means it's generally given 'as is', so aside from bug fixing it is tricky... I'm not sure something like a SaaS model would suit `chord pro`, so I just work on new features whenever I have spare time. 

I hope the new feature is useful to you :)

**Closed by shahinrostami** 2021-04-11 14:46 UTC
Labels: enhancement

**Comment by zedrdave** [comment] 2021-04-11 14:48
I hear you, and I'm perfectly happy with it as is. Merely when you feel inspired and have time for it. Good luck with everything!
